[build]
builder = "nixpacks"
buildCommand = "npm ci --include=dev && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[phases.setup]
nixPkgs = ["nodejs", "npm"] 